name: Build

on:
  pull_request: {}
  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installing Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "5.15.2"

      - name: Configure Project with QMake
        run: qmake

      - name: Build
        run: make -j$(nproc)
